name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (patch, minor, major, or specific like 1.0.1)'
        required: true
        default: 'patch'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Fetch all history for versioning
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Update version
        run: |
          if [[ "${{ github.event.inputs.version }}" =~ ^(patch|minor|major)$ ]]; then
            npm version ${{ github.event.inputs.version }}
          else
            npm version ${{ github.event.inputs.version }} --allow-same-version
          fi
      
      - name: Build package
        run: npm run build
      
      - name: List files to be published
        run: npm pack --dry-run
      
      - name: Publish to NPM
        run: |
          echo "Publishing to npm..."
          npm publish --access public
          echo "Published to npm!"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Push tags and changes
        run: |
          git push
          git push --tags 