name: Publish to npm

on:
  release:
    types: [created]
  # You can also trigger this workflow manually using the GitHub UI
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      
      - name: Print node and npm versions
        run: |
          node --version
          npm --version
      
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      
      - name: Run linting
        run: npm run lint || echo "Linting skipped"
      
      - name: Run tests
        run: npm test || echo "Tests failed but continuing"
      
      - name: Build
        run: npm run build
      
      - name: List files to be published
        run: npm pack --dry-run
      
      - name: Publish to npm
        run: |
          echo "Publishing to npm..."
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm run publish:npm
          echo "Publish completed."
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} 